### ISSUE TITLE
Singularity Engine, Supermatter Engine and Radiation.

### ISSUE THREAD

**Issue by Hawk-v3** [Repede/YawnWiderStation#121]
Singularity doesn't produce radiation. I'll bet Thaler it's because it was never switched over to the new radiation method, and still tries to use the old one.

**Comment by Hawk-v3** [comment]
SM uses snowflake code. Let's just make the fucker radiate as it should.

**Comment by DeepIndigo** [comment]
An addition notes to the singularity:

-Seemingly, simply by running at all, it can severely reduce the framerate of the server, not unlike how it used to back in the day on older code forks when admins possessed it, however in this case no possession is needed. This may be a baycode/polaris issue stemming from the build used to initially make VS, and I last witnessed it  over a year ago (up until my time here, I hadn't played since last june, and months before my absence was the last time I saw a singularity fired up on VS for this very reason). The only requirement to induce this seems to be "Having the singularity on stage 2 or higher and running", so perhaps it has to do with the code that makes the singularity pull things?

-I'm also aware that the singularity, on occasion, traverses floors (I.E. moves from asteroid 1 to Asteroid two), floating "up over" its containment grid, which I suspect has to do with how verticality works on tether (it may be pulling on objects that are in the z-level "above" due to he ability of objects to "fall", and therefor tugging its self "up"). This is of course unique to the tether map, and I'm only really aware of it through observing idle chatter in VS' code chat again, over a year ago. However to my understanding, since the singularity largely isn't used, this issue was never bothered with.

**Comment by gozulio** [comment]
So upon looking into the process() proc for the Supermatter it would appear that it solely uses the "new" radiation library. The only time it irradiates you without the radiation repository is when you touch it. If there is something generating "invisible" rads it's not the Supermatter itself.

**Comment by gozulio** [comment]
Relevant snippet of code to Singularity Radiation, it also uses the new radiation repository. It might just not be strong enough.

https://github.com/Repede/YawnWiderStation/blob/07d797011096c10849bd226eaf771ce59b7cc2ce/code/modules/power/singularity/singularity.dm#L404-L417

**Comment by Hawk-v3** [comment]
It's the second part that's doing magical toxin damage
It's using the radiation repo and then just *giving* you toxins if you're in toxin range as well
