### ISSUE TITLE
Vampirism could be improved

### ISSUE THREAD

**Issue by Hawk-v3** [Repede/YawnWiderStation#144]
#### Brief description of the issue
Only the verb for drinking blood works to feed you.

#### What you expected to happen
Drinking blood of any sort to give you nutrition and any other source to not work.

#### What actually happened
Blood from a bag or a glass ("Tomato Juice?") gives you NO nutrition at all.

#### Code Revision
https://github.com/Repede/YawnWiderStation/commit/6c2feb13bb803d2ba35decfb0a08fc5b526d6503

**Comment by Repede** [comment]
You mean harm intent > click blood bag also gives no nutrition anymore?

**Comment by Hawk-v3** [comment]
I've opened this on someone else's behalf. Not sure. I'll ask.

**Comment by Hawk-v3** [comment]
Biting bloodpacks still works.

**Comment by izac112** [comment]
Then its not a bug but it be a nice feature

**Comment by Dwaggy** [comment]
Just as a side note. Perhaps a second version (maybe one that costs points in custom races) that allows blood to be a secondary way to get nutrition, instead of a -one and only-

Reason for suggesting this?: Xenochimera has this option.
They're capable of using vampirism, but still can gain nutrition values from standard sources too.

Perhaps balance the custom trait version out by making it -cost- rather then be a neutral trait, or to lower how much nutrition you get from it.

just a side thought since vamperism is on topic.

**Comment by izac112** [comment]
I suggest adding a second version that costs and allows you to eat normal food too instead of making the current one cost because it probably break a lot of people's character seeing as then it take up a trait slot and you have to grab another negative

**Comment by Dwaggy** [comment]
Yeah. Thats what i ment, sorry. Leave the current one as is so not to fuck anyone over who wants to -stay- as a total 100% vamp with downsides too, and then make a new one that -does- cost, probably only 1 point or something small, since its a minor thing at best, considering shit like 50+ health is 3 points and all.
