### ISSUE TITLE
MobVore and it's many stupidities.

### ISSUE THREAD

**Issue by Hawk-v3** [Repede/YawnWiderStation#169]
Are there any objections to any of the following?

- Bring back the ability to attack from inside.

- Make them not just resort to vore immediately.

- Make them RESPECT the goddamn digestion preference.

**Comment by Repede** [comment]
I'd say third option is a yes.
For the others: Not sure, I know Virgo is talking about replacing the mine mobs. The goal of the mobs that are currently in the mines are meant to be expedition only mobs, which 'one shots' people who tries to rambo. And I'll agree with them on that. They are talking about making non 1shot mobs for the mines though.

**Comment by gozulio** [comment]
Considering how much of a mess the actual Vore code might be, this might be asking for a lot, because spaghetti. But if this is something that can be done with little change to upstream code then i would be all for it.

**Comment by ValiantEsp** [comment]
Third option, definitely yes, that needs to be tweaked..

 For the first... As much as it should be a thing, at the same time, it can be annoying on the other end when you eat a mob or a **mouse** and it just breaks limbs from inside. Not to mention, it discourages running off alone for expeditions.

As for the second, yeah. Pounce-nom is bullshit for all involved, and makes mimics stupidly lethal. There's no point in it except 'Fuck you, player', which the code has enough of in combat as it is.

I'd say tweak two and three, make it so most mobs have at best a chance of picking pounce out of a lineup... And so that it does as intended and spits you out if you're indigestible to attack you normally.

**Comment by Championfire** [comment]
I would say that all of them should be a thing. Even if Virgo implements mobs that don't "one-shot" you, if you're vored as is right now, you're likely stuck there for nine years since the escape chance is ridiculously low, took me five minutes to get out while spamming the resist verb.

I don't understand why not being able to attack from the inside isn't a thing, as it was already before. It makes sense for it to be a thing anyways, after all, if you're forcefully vored by something and you have a weapon of some kind, why WOULDN'T you try to get out by attacking it? With how it is now you're forced to sit there unless you escape, and the chance as I said feels too low, and some mobs have multiple bellies, which means you have to force your way to escape those extra bellies the mob may or may not have, all while hoping you're not forced back down if you do. Attacking from within should be a thing, and should be re-implemented in my opinion. 

Mobs never attacked from within so that's not really a big issue that should be worried about.

**Comment by Championfire** [comment]
And? If the person had **ooc consent for it,** and the player disarm spams and the like, then the predator can just ahelp and it's dealt with. Screwing over everyone because they can't get out of mobs since attacking from inside was removed isn't fair at all.  

Or limit it to harm intents then. Either way, it should be re-added, it makes no sense why you can't try to cut your way out or do damage if you have a weapon.

**Comment by gozulio** [comment]
Possibly relevent file of overrides.
https://github.com/Repede/YawnWiderStation/blob/8ab6a5b364b30641f50b713e1e3d71fc93c70d7d/code/modules/mob/living/simple_animal/vore/zz_vore_overrides.dm
